### ISSUE TITLE
Make the GUI of the app using PyQt5

### ISSUE THREAD

**Issue by harshsbais** [harshsbais/Amazon-Price-Drop-Alert#11]

**Comment by Vashuev** [comment]
Hello, GUI app is new for me, but I want to work on it, I saw the GUI based on Tkinter, their are some issues ( seen on the window-OS)  like:
1. The size of the window and  it's components are not fixed, 
2. no font color is their
3. Size of the font on the Button and Labels is small
4. Input box ( Entry) is too small
![amazon-price](https://user-images.githubusercontent.com/61354524/103541128-ee156900-4ec0-11eb-97e9-64171a93720a.png)

I will work on the above issues and add functionality like:
1. Status bar 
2. Pop up message, instead of rendering in the same window
3. icon ( if someone provides it)
4. Exception handling in user input

@harshsbais please assigned it, also if any there is any function that can be added in GUI please tell

**Comment by harshsbais** [comment]
Can you make the GUI using PyQt Web Engine; there seems to be some issue with TKinter on MacOS.

**Comment by Vashuev** [comment]
Yes, please assign it to me.
Thanks

**Comment by harshsbais** [comment]
I made few changes to the app, I completely deleted TKinter GUI and added basic PyQt GUI
